name: "tgchannel2blog"
services:
  postgres:
    container_name: "tgchannel2blog-postgres"
    build:
      dockerfile: ".docker/container/postgres/Dockerfile"
      context: "../../."
    environment:
      PGUSER: "${DB_USERNAME}"
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_DATABASE}"
    restart: "on-failure"
    expose:
      - "5432"
    volumes:
      - "../../var/docker/postgres:/var/lib/postgresql/data"
    ports:
      - "127.0.0.1:5432:5432"
  nats:
    build:
      dockerfile: ".docker/container/nats/Dockerfile"
      context: "../../."
    container_name: "tgchannel2blog-nats"
    restart: "on-failure"
    expose:
      - "4222"
    ports:
      - "127.0.0.1:4222:4222"
  minio:
    image: "minio/minio"
    container_name: "tgchannel2blog-minio"
    environment:
      MINIO_ACCESS_KEY: "minioadmin"
      MINIO_SECRET_KEY: "minioadmin"
    restart: "on-failure"
    expose:
      - "9000"
      - "9001"
    ports:
      - "127.0.0.1:9000:9000"
      - "127.0.0.1:9001:9001"
    volumes:
      - "../../var/docker/minio:/data"
    command: server /data --console-address ":9001"
